name: main workflow

on:
  push:

jobs:
  dependencies:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install deps
        run: |
          export LIBVIPS_VERSION_MAJOR=8
          export LIBVIPS_VERSION_MINOR=12
          export LIBVIPS_VERSION_PATCH=2
          export LIBVIPS_VERSION=$LIBVIPS_VERSION_MAJOR.$LIBVIPS_VERSION_MINOR.$LIBVIPS_VERSION_PATCH
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y automake build-essential curl gobject-introspection gtk-doc-tools libglib2.0-dev libpng-dev libjpeg-turbo8-dev \
            libwebp-dev libtiff5-dev libgif-dev libexif-dev libxml2-dev libpoppler-glib-dev swig libpango1.0-dev libmatio-dev libopenslide-dev libcfitsio-dev \
            libgsf-1-dev fftw3-dev liborc-0.4-dev librsvg2-dev libimagequant-dev

          sudo curl -L https://github.com/libvips/libvips/releases/download/v$LIBVIPS_VERSION/vips-$LIBVIPS_VERSION.tar.gz > vips-$LIBVIPS_VERSION.tar.gz
          sudo tar xf vips-$LIBVIPS_VERSION.tar.gz
          sudo ./vips-$LIBVIPS_VERSION/configure --enable-debug=no --without-python --without-magick && make && make install && ldconfig

      - name: compile binary
        run: |
          make build
      

